spring:
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://192.168.2.4:3306/bas_dev?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2b8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    ###################druid增加配置 start###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    ###################druid增加配置 end###########################
  # redis配置
  redis:
    database: 0 #redis数据库索引
    host: 127.0.0.1
    port: 6379
    password: sxgok.com
    jedis:
      pool:
        max-active: 200 #连接池最大连接数
        max-wait: -1  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10  #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
    timeout: 1000 #超时
  # 设置控制台启动时的ansi字符输出,表示可配置彩色输出
  output:
    ansi:
      enabled: always
# mybatisPlus配置
mybatis-plus:
  typeAliasesPackage: com.sxgokit.bas.entity.model
  mapperLocations: classpath:mapper/*/*.xml

# 打印sql配置日志文件路径
logging:
  level:
    com.sxgokit.bas.mapper: DEBUG
  config: classpath:logback-spring.xml
# 框架
rdf:
  # 项目启动加载系统配置表数据到redis的开关,StartupConfig
  loadConfigWhenStart: false
  # sysConfig刷新开关
  refreshConfigSwitch: true
  # sysDict刷新开关
  refreshDictSwitch: true
  server-session-timout: 86400
## APP
app:
  # token存活时间
  token-alive-time: 7200

